### ISSUE TITLE
Pràctica de ejercisios

### ISSUE THREAD

**Issue by Maricruz-Gomz** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Maricruz-Gomz#1]
[PRÁCTICA_MARI CRUZ GOMEZ CRUZ_23620080.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Maricruz-Gomz/files/12564409/PRACTICA_MARI.CRUZ.GOMEZ.CRUZ_23620080.pdf)

**Comment by DiegoLV117** [comment]
Portada 25%
Procedimiento 20%
Figuras,ilustraciones y fotografias 25%
Resultados y Clnclusiones 22%                      
 Calificacion 18/20                
  Calificado por el equipo de Elisa Sanchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
